### ISSUE TITLE
Bug whit OneVsOne Line 70

### ISSUE THREAD

**Issue by AyzrixYTB** [TheFixerDevelopment/1vs1#12]
[36m[22:32:07] [m[31m[Server thread/CRITICAL]: Error: "Using $this when not in object context" (EXCEPTION) in "1vs1/src/Minifixio/onevsone/OneVsOne" at line 70[m
[36m[22:32:07] [m[37m[Server thread/DEBUG]: #0 1vs1/src/Minifixio/onevsone/utils/PluginUtils(20): Minifixio\onevsone\OneVsOne::getMessage(string pluginprefix )[m

**Comment by TheFixerDevelopment** [comment]
Hi,
Please update to the latest Poggit build of this plugin, and try again.

**Comment by cujowilliams123** [comment]
this plugin doesnt even work it keeps crashing my server

**Comment by TheFixerDevelopment** [comment]
Hi, this should now be fixed.
Try with the latest Poggit build.
