### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by cujowilliams123** [TheFixerDevelopment/1vs1#15]
11.08 21:20:43 [Server] Server thread/CRITICAL Error: "Class 'Minifixio\onevsone\utils\PluginUtils' not found" (EXCEPTION) in "1vs1-master/src/Minifixio/onevsone/OneVsOne" at line 36
11.08 21:20:43 [Server] Server thread/DEBUG #0 src/pocketmine/plugin/PluginBase(102): Minifixio\onevsone\OneVsOne->onEnable()
11.08 21:20:43 [Server] Server thread/DEBUG #1 src/pocketmine/plugin/PluginManager(614): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
11.08 21:20:43 [Server] Server thread/DEBUG #2 src/pocketmine/Server(1931): pocketmine\plugin\PluginManager->enablePlugin(Minifixio\onevsone\OneVsOne object)
11.08 21:20:43 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1917): pocketmine\Server->enablePlugin(Minifixio\onevsone\OneVsOne object)
11.08 21:20:43 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1711): pocketmine\Server->enablePlugins(integer 1)
11.08 21:20:43 [Server] Server thread/DEBUG #5 src/pocketmine/PocketMine(237): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
11.08 21:20:43 [Server] Server thread/DEBUG #6 /pmmp_1269_1.5.0.phar(1): require(string phar:///pmmp_1269_1.5.0.phar/src/pocketmine/PocketMine.php)

**Comment by TheFixerDevelopment** [comment]
Hi, this should now be fixed.
Try with the latest Poggit build.
