### ISSUE TITLE
Plugin doesnt work - Line 74

### ISSUE THREAD

**Issue by vandermarelruben** [TheFixerDevelopment/1vs1#5]
Comes up with error:
Error: "Call to a member function get() on null" (EXCEPTION) in "1vs1.phar/src/Minifixio/onevsone/OneVsOne" at line 74
and then the plugin gets disabled.

**Comment by vandermarelruben** [comment]
I also tried downloading the version here from github and doesnt work.

**Comment by rapidofc1** [comment]
Yeah I get the same, please fix asap!!! <3

**Comment by iZeaoGamer** [comment]
Hi, thanks for reporting this bug! And sorry for the late reply.
This issue should now be fixed within the latest Poggit builds. If you happen to occur anymore bugs, please open a new issue. Thanks, issue closed.
