### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dev4uhelp** [TheFixerDevelopment/1vs1#6]
Error: "Using $this when not in object context" (EXCEPTION) in "1vs1.phar/src/Minifixio/onevsone/OneVsOne" at line 74

**Comment by TheFixerDevelopment** [comment]
Hi, thanks for reporting this bug!
This bug should now be fixed with latest builds of this plugin. Please retry and see if this is fixed or not. If it isn’t fixed, please open a new issue. Thanks.
