### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dev4uhelp** [TheFixerDevelopment/1vs1#7]
Hey after someone dies it and it announces the winner when i do / match again says your already in a arena but im in spawn

**Comment by TheFixerDevelopment** [comment]
Is there any errors during that time? If so, please copy and paste the errors log here.

**Comment by dev4uhelp** [comment]
Server thread/CRITICAL ErrorException: "include(/plugins/1vs1-master/src/Minifixio/onevsone/utils/PluginUtils.php): failed to open stream: No such file or directory" (EXCEPTION) in "vendor/pocketmine/spl/BaseClassLoader" at line 126
07.08 19:13:38 [Server] Server thread/DEBUG #0 vendor/pocketmine/spl/BaseClassLoader(126): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string include(/plugins/1vs1-master/src/Minifixio/onevsone/utils/PluginUtils.php): failed to open stream: No such file or directory, string phar:///custom.phar/vendor/pocketmine/spl/BaseClassLoader.php, integer 126, array Array())
07.08 19:13:38 [Server] Server thread/DEBUG #1 vendor/pocketmine/spl/BaseClassLoader(126): include()
07.08 19:13:38 [Server] Server thread/DEBUG #2 (): BaseClassLoader->loadClass(string Minifixio\onevsone\utils\PluginUtils)
07.08 19:13:38 [Server] Server thread/DEBUG #3 1vs1-master/src/Minifixio/onevsone/OneVsOne(36): spl_autoload_call(string Minifixio\onevsone\utils\PluginUtils)
07.08 19:13:38 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginBase(102): Minifixio\onevsone\OneVsOne->onEnable()
07.08 19:13:38 [Server] Server thread/DEBUG #5 src/pocketmine/plugin/PluginManager(611): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
07.08 19:13:38 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1931): pocketmine\plugin\PluginManager->enablePlugin(Minifixio\onevsone\OneVsOne object)
07.08 19:13:38 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1917): pocketmine\Server->enablePlugin(Minifixio\onevsone\OneVsOne object)
07.08 19:13:38 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1711): pocketmine\Server->enablePlugins(integer 1)
07.08 19:13:38 [Server] Server thread/DEBUG #9 src/pocketmine/PocketMine(237): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
07.08 19:13:38 [Server] Server thread/DEBUG #10 /custom.phar(1): require(string

**Comment by iZeaoGamer** [comment]
Hi, thanks for giving us feed back, and reporting this bug.
I tried to reproduce this issue, but I'm unable to. You never gave me the errors log, and such. Unfortunately, I can't fix this without reproducing, or giving any error logs, and such.
If you feel it should be open, then please reply here, and I'll reopen it.
Issue closed.
